name: droame
description: Droame Hackathon.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0-406.0.dev <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  animated_splash_screen: ^1.3.0
  lottie: ^2.0.0
  flutter_dotenv: ^5.0.2
  http: ^0.13.5
  firebase_auth: ^4.1.2
  cloud_firestore: ^4.0.5
  firebase_core: ^2.2.0
  firebase_phone_auth_handler: ^1.0.7
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/illustrations/
    - assets/lottie.json